version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  gateway-service:
    image: xom4ik/rsoi-gateway-service:latest
    container_name: rsoi_gateway-service
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./configs/gateway-service/appsettings.json:/app/appsettings.json
    environment:
      - INIT_DATABASE=true
      - ASPNETCORE_ENVIRONMENT=Production

  reservation-service:
    image: xom4ik/rsoi-reservation-service:latest
    container_name: reservation-service
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - "8070:8070"
    volumes:
      - ./configs/reservation-service/appsettings.json:/app/appsettings.json
    environment:
      - INIT_DATABASE=true
      - ASPNETCORE_ENVIRONMENT=Production

  library-service:
    image: xom4ik/rsoi-library-service:latest
    container_name: library-service
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - "8060:8060"
    volumes:
      - ./configs/library-service/appsettings.json:/app/appsettings.json
    environment:
      - INIT_DATABASE=true
      - ASPNETCORE_ENVIRONMENT=Production

  rating-service:
    image: xom4ik/rsoi-rating-service:latest
    container_name: rating-service
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - "8050:8050"
    volumes:
      - ./configs/rating-service/appsettings.json:/app/appsettings.json
    environment:
      - INIT_DATABASE=true
      - ASPNETCORE_ENVIRONMENT=Production
volumes:
  db-data: