{{- if .Values.keycloak.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.keycloak.name }}-svc
spec:
  selector:
    app: {{ .Values.keycloak.name }}
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: {{ .Values.keycloak.service.nodePort }}
  type: {{ .Values.keycloak.service.type }}
{{- end }}